/* Automatically generated file - do not edit */

#include "qe.h"
#include "css.h"

const char docbook_style[] = {
    "abstract,ackno,address,affiliation,alt,answer,appendix,areaspec,"
    "arg,article,attribution,audioobject,author,authorblurb,authorgro"
    "up,beginpage,bibliodiv,biblioentry,bibliography,bibliomixed,bibl"
    "iomset,biblioset,blockquote,book,bookbiblio,bridgehead,callout,c"
    "alloutlist,caption,caution,chapter,city,cmdsynopsis,collab,colop"
    "hon,comment,confdates,confgroup,confnum,confsponsor,conftitle,co"
    "ntractnum,contractsponsor,contrib,copyright,corpauthor,corpname,"
    "country,dedication,edition,editor,epigraph,equation,example,figu"
    "re,firstname,footnote,formalpara,funcprototype,funcsynopsis,func"
    "synopsisinfo,glossary,glossdef,glossentry,glosslist,glosssee,glo"
    "ssseealso,graphic,graphicco,group,highlights,holder,honorific,im"
    "ageobject,imageobjectco,important,index,indexdiv,indexentry,info"
    "rmalequation,informalexample,informalfigure,issuenum,itemizedlis"
    "t,itermset,jobtitle,keywordset,legalnotice,lineage,listitem,lite"
    "rallayout,lot,lotentry,mediaobject,mediaobjectco,member,msg,msga"
    "ud,msgentry,msgexplan,msginfo,msglevel,msgmain,msgorig,msgrel,ms"
    "gset,msgsub,msgtext,note,orderedlist,otheraddr,othercredit,other"
    "name,para,part,partintro,phone,pob,postcode,preface,primaryie,pr"
    "inthistory,procedure,programlisting,programlistingco,publisher,p"
    "ublishername,qandadiv,qandaentry,qandaset,question,refclass,refd"
    "escriptor,refentry,refentrytitle,reference,refmiscinfo,refname,r"
    "efnamediv,refsect1,refsect2,refsect3,refsynopsisdiv,releaseinfo,"
    "revhistory,revision,revremark,sbr,screen,screenco,screenshot,sec"
    "ondaryie,sect1,sect2,sect3,sect4,sect5,section,seealsoie,seeie,s"
    "eglistitem,segmentedlist,set,setindex,shortaffil,sidebar,simpara"
    ",simplelist,simplesect,state,step,street,subject,subjectset,subj"
    "ectterm,substeps,subtitle,surname,synopfragment,synopfragmentref"
    ",synopsis,term,tertiaryie,textobject,tip,title,toc,tocback,tocch"
    "ap,tocentry,tocfront,toclevel1,toclevel2,toclevel3,toclevel4,toc"
    "level5,tocpart,variablelist,varlistentry,videoobject,warning{dis"
    "play:block;}articleinfo,bookinfo,docinfo,objectinfo,refmeta,refs"
    "ect1info,refsect2info,refsect3info,refsynopsisdivinfo,screeninfo"
    ",sect1info,sect2info,sect3info,sect4info,sect5info,sectioninfo,s"
    "etinfo,titleabbrev,indexterm{display:none;}chapter>title,glossar"
    "y>title{font-size:2em;font-weight:bold;color:maroon;margin-top:."
    "67ex;margin-bottom:.67ex;}chapter{counter-increment:chap;counter"
    "-reset:sect1}chapter>title:before{content:\"Chapter \"counter(ch"
    "ap,upper-roman)\"\\A\";}article>title{font-size:2em;margin-top:."
    "67ex;margin-bottom:.67ex;text-align:center;}subtitle{font-weight"
    ":bold;color:maroon;margin-top:1.33ex;margin-bottom:1.33ex;}artic"
    "le>subtitle{text-align:center;}sect1>title,sect2>title,sect3>tit"
    "le,sect4>title,sect5>title,section>title{font-weight:bold;color:"
    "maroon;}sect1>title,section>title{font-size:1.5em;margin-top:.83"
    "ex;margin-bottom:.83ex;}sect2>title,section section>title{font-s"
    "ize:1.17em;margin-top:1ex;margin-bottom:1ex;}sect3>title,sect4>t"
    "itle,sect5>title,section section section>title,section section*s"
    "ection>title{font-size:1em;margin-top:1.33ex;margin-bottom:1.33e"
    "x;}sect1,section{counter-increment:sect1}sect1>title:before,sect"
    "ion>title:before{content:counter(chap)\".\"counter(sect1)\" \";}"
    "sect2,section section{counter-increment:sect2}sect2>title:before"
    ",section section>title:before{content:counter(chap)\".\"counter("
    "sect1)\".\"counter(sect2)\" \";}sect3,section section section{co"
    "unter-increment:sect3}sect3>title:before,section section section"
    ">title:before{content:counter(chap)\".\"counter(sect1)\".\"count"
    "er(sect2)\".\"counter(sect3)\" \";}sect4,section section section"
    " section{counter-increment:sect4}sect4>title:before,section sect"
    "ion section section>title:before{content:counter(chap)\".\"count"
    "er(sect1)\".\"counter(sect2)\".\"counter(sect3)\".\"counter(sect"
    "4)\" \";}section section section*section>title:before{content:\""
    "\";}table,informaltable{display:block;margin-top:1.33ex;margin-b"
    "ottom:1.33ex;}table>title{font-style:italic;text-align:center;ma"
    "rgin-left:2ex;margin-right:2ex;margin-bottom:2ex;}tgroup{display"
    ":table;border:1px outset gray;text-align:eval(attr(align));}cols"
    "pec,spanspec{display:table-column;}thead,tbody,tfoot{display:tab"
    "le-row-group;vertical-align:eval(attr(valign));}row{display:tabl"
    "e-row;vertical-align:eval(attr(valign));}entry{display:table-cel"
    "l;text-align:eval(attr(align));vertical-align:eval(attr(valign))"
    ";border:1px inset gray;padding:2px;}entry>*:first-child{margin-t"
    "op:0;margin-bottom:0;}entrytbl{display:table;border:1px inset gr"
    "ay;padding:2px;}para,simpara,formalpara{margin-top:1.33ex;margin"
    "-bottom:1.33ex;}formalpara>*{margin-top:0;margin-bottom:0;}forma"
    "lpara>title{font-weight:bold;}listitem>*:first-child{margin-top:"
    "0;margin-bottom:0;}itemizedlist{margin-left:2ex;margin-top:1.33e"
    "x;margin-bottom:1.33ex;}itemizedlist>listitem{margin-left:2.5ex;"
    "}itemizedlist>listitem:before{display:marker;content:disc;}itemi"
    "zedlist>listitem itemizedlist>listitem:before{display:marker;con"
    "tent:square;}itemizedlist>listitem itemizedlist>listitem itemize"
    "dlist>listitem:before{display:marker;content:icon(diamond);}item"
    "izedlist>listitem itemizedlist>listitem itemizedlist>listitem it"
    "emizedlist>listitem:before{display:marker;content:circle;}ordere"
    "dlist{margin-left:2ex;margin-top:1.33ex;margin-bottom:1.33ex;}or"
    "deredlist>listitem{margin-left:6ex;}orderedlist>listitem:before{"
    "display:marker;counter-increment:n;content:counter(n,decimal);fo"
    "nt-weight:bold;}orderedlist[numeration=loweralpha]>listitem:befo"
    "re{display:marker;content:counter(n,lower-alpha);counter-increme"
    "nt:n;}orderedlist[numeration=upperalpha]>listitem:before{display"
    ":marker;content:counter(n,upper-alpha);counter-increment:n;}orde"
    "redlist[numeration=lowerroman]>listitem:before{display:marker;co"
    "unter-increment:n;content:counter(n,lower-roman);}orderedlist[nu"
    "meration=upperroman]>listitem:before{display:marker;counter-incr"
    "ement:n;content:counter(n,upper-roman);}variablelist{margin-left"
    ":2ex;margin-top:1.33ex;margin-bottom:1.33ex;}varlistentry>term{f"
    "ont-weight:bold;}varlistentry>listitem{margin-left:4ex;}glossent"
    "ry{margin-top:1.33ex;margin-bottom:1.33ex;}glossentry>glossterm{"
    "display:block;font-style:italic;}glossdef{margin-left:4ex;}gloss"
    "def>*:first-child{margin-top:0;margin-bottom:0;}qandaentry{margi"
    "n-top:1.33ex;margin-bottom:1.33ex;}question{font-style:italic;}q"
    "uestion,answer{margin-left:4ex;}question:before{content:\"Q:\";d"
    "isplay:marker;color:olive;font-weight:bold;font-style:normal;}an"
    "swer:before{content:\"A:\";display:marker;color:olive;font-weigh"
    "t:bold;}question>*:first-child,answer>*:first-child{margin-top:0"
    ";margin-bottom:0;}simplelist{margin-left:4ex;}member{margin-left"
    ":2.5ex;}note{margin-left:10ex;}note:before{content:\"note \";dis"
    "play:marker;color:olive;}tip{margin-left:10ex;}tip:before{conten"
    "t:\"tip \";display:marker;color:olive;}footnote{font-size:.83em;"
    "margin-left:15ex;margin-right:5ex;}footnote:before{content:\"foo"
    "tnote \";display:marker;color:olive;}programlisting,screen{white"
    "-space:pre;background-color:#E0E0E0;border:thin solid gray;font-"
    "family:monospace;font-size:.83em;margin-top:1.33ex;margin-bottom"
    ":1.33ex;}programlistingco{border:1 solid gray;padding:1ex;margin"
    "-top:1.33ex;margin-bottom:1.33ex;}programlistingco programlistin"
    "g{border-style:none;}areaspec:before{content:\"areas \";color:ol"
    "ive;}area,co{counter-increment:n;content:\"(\"counter(n)\")\";co"
    "lor:olive;}callout{margin-left:6ex;}callout>*:first-child{margin"
    "-top:0;margin-bottom:0;}calloutlist>callout:before{display:marke"
    "r;counter-increment:n;content:\"(\"counter(n)\")\";color:olive;}"
    "figure,mediaobject{text-align:center;margin-left:auto;margin-rig"
    "ht:auto;margin-top:1.33ex;margin-bottom:1.33ex;}figure>title,cap"
    "tion{font-style:italic;}caption>*:first-child{margin-top:0;margi"
    "n-bottom:0;}graphic,imagedata{content:image(attr(fileref),-400,-"
    "200);}graphic{margin-left:auto;margin-right:auto;}blockquote{mar"
    "gin-left:10ex;margin-right:10ex;margin-top:1.33ex;margin-bottom:"
    "1.33ex;}blockquote>title,attribution{font-style:italic;}attribut"
    "ion{text-align:right;}attribution:before{content:\"-- \"}emphasi"
    "s{font-style:italic;}emphasis[role=bold]{font-style:normal;font-"
    "weight:bold;}literal,filename,command,envar,parameter{font-famil"
    "y:monospace;font-size:.83em;}parameter,replaceable{font-style:it"
    "alic;}anchor:after{content:icon(left-target);vertical-align:text"
    "-top;color:olive;}link,ulink,email{color:navy;text-decoration:un"
    "derline;}xref{content:icon(right-link);vertical-align:text-top;c"
    "olor:navy;}foreignphrase{font-style:italic;}sgmltag{color:red;}s"
    "gmltag[class=\"starttag\"]:before{content:\"<\";}sgmltag[class=\""
    "endtag\"]:before{content:\"</\";}sgmltag[class=\"starttag\"]:aft"
    "er,sgmltag[class=\"endtag\"]:after{content:\">\";}quote:before{c"
    "ontent:open-quote;}quote:after{content:close-quote;}@media print"
    "{articleinfo,bookinfo,docinfo,objectinfo,refmeta,refsect1info,re"
    "fsect2info,refsect3info,refsynopsisdivinfo,screeninfo,sect1info,"
    "sect2info,sect3info,sect4info,sect5info,sectioninfo,setinfo,titl"
    "eabbrev,indexterm{display:none;}colspec,spanspec{display:none;}*"
    "{background-color:transparent;line-height:1.2;}programlisting,sc"
    "reen{background-color:#FFFFE0;border:1px solid#E0E0A0;}graphic,i"
    "magedata{content:image(attr(fileref),-500,-700,smooth);}}"
};

