/* Automatically generated file - do not edit */

#include "qe.h"
#include "css.h"

const char html_style[] = {
    "address,blockquote,body,dd,div,dl,dt,fieldset,form,frame,framese"
    "t,h1,h2,h3,h4,h5,h6,iframe,noframes,object,ol,p,ul,applet,center"
    ",dir,hr,menu,pre{display:block}li{display:list-item}head{display"
    ":none}table{display:table;border-collapse:separate;border-spacin"
    "g:2px;text-align:left;}tr{display:table-row;vertical-align:middl"
    "e}thead{display:table-header-group}tbody{display:table-row-group"
    "}tfoot{display:table-footer-group}col{display:table-column}colgr"
    "oup{display:table-column-group}td,th{display:table-cell;vertical"
    "-align:inherit}caption{display:table-caption}th{font-weight:bold"
    "er;text-align:center}caption{text-align:center}body{padding:8px;"
    "}h1{font-size:2em;margin:.67em 0}h2{font-size:1.5em;margin:.83em"
    " 0}h3{font-size:1.17em;margin:1em 0}h4,p,blockquote,ul,fieldset,"
    "form,ol,dl,dir,menu{margin:1.33em 0}h5{font-size:.83em;line-heig"
    "ht:1.17em;margin:1.67em 0}h6{font-size:.67em;margin:2.33em 0}h1,"
    "h2,h3,h4,h5,h6,b,strong{font-weight:bolder}blockquote{margin-lef"
    "t:40px;margin-right:40px}i,cite,em,var,address{font-style:italic"
    "}pre,tt,code,kbd,samp{font-family:monospace}pre{white-space:pre}"
    "big{font-size:1.17em}small,sub,sup{font-size:.83em}sub{vertical-"
    "align:sub}sup{vertical-align:super}s,strike,del{text-decoration:"
    "line-through}hr{border:#555 1px inset}ol,ul,dir,menu,dd{margin-l"
    "eft:40px}ol{list-style-type:decimal}ol ul,ul ol,ul ul,ol ol{marg"
    "in-top:0;margin-bottom:0}u,ins{text-decoration:underline}center{"
    "text-align:center}br:before{content:\"\\A\"}nobr{white-space:now"
    "rap}td[nowrap]{white-space:nowrap}a[href]{text-decoration:underl"
    "ine;color:blue}bdo[dir=\"ltr\"]{direction:ltr;unicode-bidi:bidi-"
    "override}bdo[dir=\"rtl\"]{direction:rtl;unicode-bidi:bidi-overri"
    "de}*[dir=\"ltr\"]{direction:ltr;unicode-bidi:embed}*[dir=\"rtl\""
    "]{direction:rtl;unicode-bidi:embed}address,blockquote,body,dd,di"
    "v,dl,dt,fieldset,form,frame,frameset,h1,h2,h3,h4,h5,h6,iframe,no"
    "script,noframes,object,ol,p,ul,applet,center,dir,hr,menu,pre,li,"
    "table,tr,thead,tbody,tfoot,col,colgroup,td,th,caption{unicode-bi"
    "di:embed}body{color:black;}input,button,img,select{display:inlin"
    "e-block;}input[type=\"hidden\"]{display:none}input[type=\"radio\""
    "]:before{content:\"(*)\";white-space:pre}input[type=\"checkbox\""
    "]:before{content:\"[X]\";white-space:pre}input[type=\"button\"],"
    "input[type=\"reset\"],input[type=\"submit\"],button{color:black;"
    "background-color:gray;padding:4px;border:3px ridge}input[type=\""
    "text\"],input[type=\"password\"],input[type=\"file\"],textarea{c"
    "olor:black;background-color:white;padding:2px;border:3px ridge;f"
    "ont-size:14pt;font-family:monospace;white-space:pre;text-align:l"
    "eft;}input[type=\"file\"]{width:20em;}textarea{display:block}sel"
    "ect{color:black;background-color:white;padding:2px;border:3px ri"
    "dge;font-size:14pt;width:6em;}option{display:none}option[selecte"
    "d]{display:inline}optgroup{display:none}img,input[type=\"img\"]{"
    "font-family:sans;font-size:10pt;vertical-align:top;text-align:le"
    "ft;overflow:hidden;text-decoration:none;}ul,ol{list-style-positi"
    "on:outside}table{list-style-position:inside}body{list-style-posi"
    "tion:inside}ul,ol{counter-reset:list-item}"
};

